// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://monxqvenifweuvcqhyby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vbnhxdmVuaWZ3ZXV2Y3FoeWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NTI3OTMsImV4cCI6MjA3MTIyODc5M30.uJbzZ6p2KEElMpz8z1OMtoPp1M2JjXmbwjJ7F4zfh0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});